on:
# Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
      repo_name:
        required: true
        type: string
        default: "my-ecr-repo"
    secrets:
      registry_username: 
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "start build"
        run: echo "building docker image"
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: ${{ secrets.rolename  }}
          aws-region: ${{ secrets.target_region }} 
      - name: connect to account
        run: aws s3 ls
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ secrets.ACCOUNT_ID }}
      - name: "create ECR repository"
        uses: int128/create-ecr-repository-action@v1
        with:
          repository: ${{inputs.repo_name}}
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{inputs.repo_name}}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    
