on:
# Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
    secrets:
      registry_username: 
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "start build"
        run: echo "building docker image"
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: ${{ secrets.rolename  }}
          aws-region: ${{ secrets.target_region }} 
      - name: connect to account
        run: aws s3 ls
     
    
